<?php
declare(strict_types=1);
namespace robske_110\voltronicaxpert\protocol;

abstract class DeviceFlag{
	const BUZZER_FLAG = "a";
	const OVERLOAD_BYPASS_FLAG = "b";
	const POWER_SAVING_FLAG = "j";
	const LCD_DISPLAY_DEFAULT_PAGE_TIMEOUT_FLAG = "k";
	const OVERLOAD_RESTART_FLAG = "u";
	const OVER_TEMPERATURE_RESTART_FLAG = "v";
	const BACKLIGHT_FLAG = "x";
	const ALARM_PRIMARY_SOURCE_INTERRUPT_FLAG = "y";
	const FAULT_CODE_RECORD_FLAG = "z";
	
	const FLAGS = [
		self::BUZZER_FLAG => "BUZZER",
		self::OVERLOAD_BYPASS_FLAG => "OVERLOAD_BYPASS",
		self::POWER_SAVING_FLAG => "POWER_SAVING",
		self::LCD_DISPLAY_DEFAULT_PAGE_TIMEOUT_FLAG => "LCD_DISPLAY_RETURN_DEFAULT_PAGE_TIMEOUT",
		self::OVERLOAD_RESTART_FLAG => "OVERLOAD_RESTART",
		self::OVER_TEMPERATURE_RESTART_FLAG => "OVER_TEMPERATURE_RESTART",
		self::BACKLIGHT_FLAG => "BACKLIGHT",
		self::ALARM_PRIMARY_SOURCE_INTERRUPT_FLAG => "ALARAM_PRIMARY_SOURCE_INTERRUPT",
		self::FAULT_CODE_RECORD_FLAG => "FAULT_CODE_RECORD"
	];
}