<?php
declare(strict_types=1);
namespace robske_110\voltronicaxpert\protocol;

abstract class SetCommandID{
	const DEVICE_FLAG_STATUS = "P";
	const DEVICE_OUTPUT_FREQUENCY = "F";
	const DEVICE_OUTPUT_SOURCE_PRIORITY = "POP";
	const BATTERY_RECHARGE_VOLTAGE = "PBCV";
	const BATTERY_REDISCHARGE_VOLTAGE = "PBDV";
	const DEVICE_CHARGER_PRIORITY = "PCP";
	const DEVICE_GRID_WORKING_RANGE = "PGR";
	const BATTERY_TYPE = "PBT";
	const BATTERY_CUTOFF_VOLTAGE = "PSDV";
	const BATTERY_CV_VOLTAGE = "PCVV";
	const BATTERY_FLOAT_VOLTAGE = "PBFT";
	const PV_OK_CONDITION = "PPVOKC";
	const SOLAR_POWER_BALANCE = "PSPB";
	const MAX_PARALLEL_CHARGING_CURRENT = "MCHGC";
	const MAX_PARALLEL_UTILITY_CHARGING_CURRENT = "MUCHGC";
	const OUTPUT_MODE = "POPM";
	const DEVICE_PARALLEL_DEVICE_CHARGER_PRIORITY = "PCP";
	const MAX_PARALLEL_CHARGING_CURRENT_EXTENDED = "MNCHGC"; //above 100A
}
